name : Build-Artifacts
    
on: workflow_dispatch

jobs: 
    build-macos:
        name: build install urho.Net macOS
        runs-on: macos-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                submodules: recursive
            - name: Dotnet setup
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: '6.0.x'
            - name: Select xcode
              run: sudo xcode-select --switch /Applications/Xcode_14.0.1.app
            - name: build and install macos urho.Net libs
              run : ./Source/script/build_install_urhonet_macos.sh

            - name: Create artifact directory
              run:  |
                mkdir -p build-macos/template/libs/dotnet/urho
                mkdir -p build-macos/template/libs
           
            - name: Copy files to artifact directory
              run: |
                  cp -R template/libs/dotnet/urho/desktop build-macos/template/libs/dotnet/urho
                  cp -R template/libs/macos build-macos/template/libs

            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                 name: build-macos
                 path: | 
                    build-macos

    build-Linux:
        name: build install urho.Net Linux
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                submodules: recursive
            - name: Dotnet setup
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: '6.0.x'
            - name: Install dependencies
              run: sudo apt-get install -y libgl1-mesa-dev libegl1-mesa-dev mesa-common-dev xorg-dev libasound-dev
            - name: build and install Linux urho.Net libs
              run : ./Source/script/build_install_urhonet_linux.sh

            - name: Create artifact directory
              run:  mkdir -p build-Linux/template/libs

            - name: Copy files to artifact directory
              run: cp -R template/libs/linux build-Linux/template/libs

            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                 name: build-Linux
                 path: | 
                    build-Linux
                  
   
    # build-Windows:
    #     name: build install urho.Net Windows
    #     runs-on: windows-latest
    #     steps:
    #          - name: Checkout repository
    #            uses: actions/checkout@v3
    #            with:
    #              submodules: recursive
    #          - name: Dotnet setup
    #            uses: actions/setup-dotnet@v1
    #            with:
    #              dotnet-version: '6.0.x'
    #          - name: Install and Configure Mono
    #            run: pwsh -File ./Source/script/install_mono.ps1
    #          - name: Install Visual Studio 2019 Build Tools
    #            run: |
    #             choco install visualstudio2019buildtools --package-parameters "--allWorkloads --includeRecommended --includeOptional"
    #             choco install visualstudio2019-workload-vctools --package-parameters "--includeRecommended --includeOptional"
    #          - name: build and install Windows urho.Net libs
    #            run : pwsh -File ./Source/script/build_install_urhonet_windows.ps1
    #          - name: Upload Artifacts
    #            uses: actions/upload-artifact@v3
    #            with:
    #               name: build-Windows
    #               path: | 
    #                 template/libs/windows

    # build-android-linux:
    #     name: build install Android Urho.Net on Linux
    #     runs-on: ubuntu-latest
    #     steps:
    #        - name: Checkout repository
    #          uses: actions/checkout@v3
    #          with:
    #             submodules: recursive
    #        - name: Set up JDK 11
    #          uses: actions/setup-java@v2
    #          with:
    #             java-version: '11'
    #             distribution: 'adopt'
    #        - name: Print Java version
    #          run: echo $JAVA_HOME
    #        - name: Setup Android SDK and NDK
    #          run : ./Source/script/setup_android_linux.sh
    #        - name: Install CMake
    #          run: sudo apt-get install cmake
    #        - name: Use cmake
    #          run: cmake --version
    #        - name: build and install Android urho.Net libs
    #          run : ./Source/script/build_install_urhonet_android_libs.sh
    #        - name: Upload Artifacts
    #          uses: actions/upload-artifact@v3
    #          with:
    #             name: build-android-linux
    #             path: | 
    #               template/libs/dotnet/urho/mobile/android
    #               template/libs/android/arm64-v8a
    #               template/libs/android/armeabi-v7a
    #               template/libs/android/x86
    #               template/libs/android/x86_64
    #               template/Android/classes 

    # build-ios:
    #     name: build install urho.Net iOS
    #     runs-on: macos-latest
    #     steps:
    #        - name: Checkout repository
    #          uses: actions/checkout@v3
    #          with:
    #             submodules: recursive
    #        - name: Dotnet setup
    #          uses: actions/setup-dotnet@v1
    #          with:
    #             dotnet-version: '6.0.x'
    #        - name: Select xcode
    #          run: sudo xcode-select --switch /Applications/Xcode_14.0.1.app
    #        - name: build and install ios urho.Net libs
    #          run : ./Source/script/build_install_urhonet_ios.sh
    #        - name: Upload Artifacts
    #          uses: actions/upload-artifact@v3
    #          with:
    #               name: build-ios
    #               path: | 
    #                 template/IOS
    #                 template/libs/ios/urho3d/gles/release
    #                 template/libs/ios/urho3d/gles/debug
    #                 template/libs/ios/urho3d/metal/release
    #                 template/libs/ios/urho3d/metal/debug
    #                 template/libs/dotnet/urho/mobile/ios

    create-artifacts:
           name: Create combined artifacts
           runs-on: ubuntu-latest
           needs: [build-macos, build-Linux]
           steps:
              - name: Create artifacts directory
                run: mkdir artifacts

              - name: Download macOS artifacts
                uses: actions/download-artifact@v3
                with:
                 name: build-macos
                 path: artifacts

              - name: Download Linux artifacts
                uses: actions/download-artifact@v3
                with:
                   name: build-Linux
                   path: artifacts


              - name: Upload combined artifacts
                uses: actions/upload-artifact@v3
                with:
                  name: combined-artifacts
                  path: artifacts


    #           - name: Download Windows artifacts
    #             uses: actions/download-artifact@v3
    #             with:
    #                name: build-Windows
    #                path: artifacts

    #           - name: Download Android artifacts
    #             uses: actions/download-artifact@v3
    #             with:
    #                   name: build-android-linux
    #                   path: artifacts

    #           - name: Download iOS artifacts
    #             uses: actions/download-artifact@v3
    #             with:
    #                 name: build-ios
    #                 path: artifacts

    #           - name: Combine artifacts
    #             run: tar -czvf combined-artifacts.tar.gz -C artifacts .

    #           - name: Upload combined artifacts
    #             uses: actions/upload-artifact@v3
    #             with:
    #               name: combined-artifacts
    #               path: combined-artifacts.tar.gz
