name : Build
    
on: workflow_dispatch

jobs: 
#     build-macos:
#         name: build install urhonet macOS
#         runs-on: macos-latest
#         steps:
#             - name: Checkout repository
#               uses: actions/checkout@v2
#               with:
#                 submodules: recursive
#             - name: Dotnet setup
#               uses: actions/setup-dotnet@v1
#               with:
#                 dotnet-version: '6.0.x'
#             - name: Setup Java
#               uses: actions/setup-java@v2
#               with:
#                 distribution: 'microsoft'
#                 java-version: '11' 
#             - name: Select xcode
#               run: sudo xcode-select --switch /Applications/Xcode_14.0.1.app
#             - name: build and install macos urhonet libs
#               run : ./Source/script/build_install_urhonet_macos.sh

    # build-Linux:
    #     name: build install urhonet Linux
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout repository
    #           uses: actions/checkout@v2
    #           with:
    #             submodules: recursive
    #         - name: Dotnet setup
    #           uses: actions/setup-dotnet@v1
    #           with:
    #             dotnet-version: '6.0.x'
    #         - name: Install OpenGL development libraries
    #           run: sudo apt-get install libgl1-mesa-dev -y
    #         - name: build and install Linux urhonet libs
    #           run : ./Source/script/build_install_urhonet_linux.sh

                  
    build-Windows:
        name: build install urhonet Windows
        runs-on: windows-latest
        steps:
             - name: Checkout repository
               uses: actions/checkout@v2
               with:
                 submodules: recursive
             - name: Dotnet setup
               uses: actions/setup-dotnet@v1
               with:
                 dotnet-version: '6.0.x'
             - name: Install mono
               run : choco install mono
             - name: Configure Mono Environment
               run: |
                 echo 'export PATH="/c/Program Files/Mono/bin:$PATH"' >> $GITHUB_ENV
                 echo 'export FrameworkPathOverride="/c/Program Files/Mono/lib/mono/4.5"' >> $GITHUB_ENV  
             - name: Install Visual Studio 2019 Build Tools
               run: |
                choco install visualstudio2019buildtools --package-parameters "--allWorkloads --includeRecommended --includeOptional"
                choco install visualstudio2019-workload-vctools --package-parameters "--includeRecommended --includeOptional"
             - name: build and install Windows urhonet libs
               run : pwsh -File ./Source/script/build_install_urhonet_windows.ps1